[package]
name = "badge-cache"
version = "0.1.0"
authors = ["James Kominick <james.kominick@gmail.com>"]

[[bin]]
name = "badge-cache"
path = "src/main.rs"
doc = false

[dependencies]
clap = "2"
dotenv = "0.8"
lazy_static = "0.2"

chrono = { version = "0.3", features = ["serde"] }

#tera = "0.10"

serde = "1"
serde_derive = "1"
serde_json = "1"

#diesel = { version = "0.13", features = ["postgres", "chrono"] }
#diesel_codegen = { version = "0.13", features = ["postgres"] }
#
#r2d2 = "0.7"
#r2d2-diesel = "0.13"

iron = "*"
router = "*"
logger = "*"
persistent = "*"
staticfile = "*"
mount = "*"

mime = "0.2"
params = "0.6"
